### ISSUE TITLE
Multi-line BREAKING CHANGE does not work

### ISSUE THREAD

**Issue by NickDub** [tomtom-international/commisery-action#261]
A picture is more explicit than a long speech:

- 1 line => OK: 
![image](https://github.com/tomtom-international/commisery-action/assets/20282929/849b0c76-5bd5-445b-979c-0a750ec7456f)

- 3 lines => KO: 
![image](https://github.com/tomtom-international/commisery-action/assets/20282929/75a05f99-888d-4a82-89c8-668c74b1c659)

**Comment by jstmlr** [comment]
Hi Nicolas, the reason the second example does not work is that Commisery only searches for `BREAKING CHANGE` statements in the "commit message footer".
It has defined the "footer" as a collection of [Git trailers](https://git-scm.com/docs/git-interpret-trailers). Multiline trailers are therein defined as:
> The value may be split over multiple lines with each subsequent line starting with at least one whitespace, like the "folding" in RFC 822.

Therefore, when you start a new line that doesn't start with whitespace and that does not look like a Git commit trailer itself, it and everything above it is assumed to be part of the commit body, and thus not scanned for `BREAKING CHANGE` statements.

Starting the line(s) after the `BREAKING CHANGE` with at least one whitespace character will solve your issue:
```diff
BREAKING CHANGE: move "opus-healthcheck" to "opus-common" repository
 bump node version from 10.19.0 to 18.15.0
 update all dependencies
```

**Comment by NickDub** [comment]
OK, thanks for the explanation.
I didn't know that rule...
